// flow-typed signature: 12ac223224c9cb051709650dfe02e408
// flow-typed version: <<STUB>>/karma-notify-reporter_v^1.0.1/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'karma-notify-reporter'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'karma-notify-reporter' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'karma-notify-reporter/index' {
  declare module.exports: $Exports<'karma-notify-reporter'>;
}
declare module 'karma-notify-reporter/index.js' {
  declare module.exports: $Exports<'karma-notify-reporter'>;
}
